config/routes.rb
Group::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope '(:locale)' do

    resources :categories do
      resources :posts
    end

    resources :contacts

    root 'categories#home'

    get "/contact" => "contacts#aweberform", as: "aweberform"
    get "/posts/search" => "posts#search"

    get "/courses" => "contents#courses"
    get "/method" => "contents#method"
    get "/thank-you-courses" => "contents#thankyoucourses", as: "thankyoucourses"
    get "/thank-you-products" => "contents#thankyouproducts", as: "thankyouproducts"
    get "/memberships" => "contents#memberships"
    get "/why-choose-us" => "contents#chooseus", as: "chooseus"
    get "/success-stories" => "contents#stories", as: "stories"
    get "/resources" => "contents#resources", as: "resources"
    get "/terms-and-conditions" => "contents#terms", as: "terms"
    get "/privacy" => "contents#privacy"

  end
  

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :posts

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	# adding some validations
	validates :name, presence: true
	validates :email, presence: true
	validates :subject, presence: true
	validates :comments, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :category

	has_attached_file :image, styles: { header: '620x200#' }

	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/jpg', 'image/png']


	# It returns the Posts whose titles contain one or more words that form the query
	def self.search(query)
	    # where(:title, query) -> This would return an exact match of the query
	    where("title like ?", "%#{query}%") 
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :set_i18n_locale_from_params
	# ...
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	# ...

	protected
	def set_i18n_locale_from_params
		if params[:locale]
			if I18n.available_locales.map(&:to_s).include?(params[:locale])
				I18n.locale = params[:locale]
			else
				flash.now[:notice] =
					"#{params[:locale]} translation not available"
				logger.error flash.now[:notice]
			end
		end
	end

	def default_url_options
		{ locale: I18n.locale }		
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :get_categories

  def index
        
    @posts = Post.order('created_at desc').limit(10)

  end

  def show
    
  	@category = Category.find(params[:id])

  end

  def home
  	if params[:set_locale]
  		redirect_to root_url(locale: params[:set_locale])
  	else
      
      @posts = Post.order('created_at desc').limit(2)

  	end
  end


  def get_categories
    # for the partial list of categories
    @categories = Category.all.order("rank asc, name asc")    
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def aweberform
  end
<<<<<<< HEAD
=======
  
>>>>>>> slideOK

  def new
  	@contact = Contact.new
  end


  # POST /users
  # POST /users.json
  def create
    @contact = Contact.new(contact_params)
 
    respond_to do |format|
      if @contact.save
        # Tell the UserMailer to send an Email after save
        ContactMail.contact_email(@contact).deliver
        ContactMail.admin_email(@contact).deliver
 		
 		   flash[:success] = "Message was successfully sent."
        
        format.html { redirect_to new_contact_path }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        flash[:error] = "Message was NOT successfully sent."

        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def contact_params
  	params.require(:contact).permit(:name, :email, :phone, :subject, :comments)
  end


end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def courses
  end

  def method
  end

  def memberships
  end

  def chooseus
  end

  def stories
  end

  def resources
  end

  def thankyoucourse
  end

  def thankyouproduct
  end

  def terms
  end

  def privacy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    # for the partial list of categories
    @categories = Category.all.order("rank asc, name asc")
    # to find the right category and then find the correspondent post...
    @category = Category.find(params[:category_id])
    
    @post = @category.posts.find(params[:id])
  end

  def search
    # for the partial list of categories
    @categories = Category.all.order("rank asc, name asc")

    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.order("created_at DESC")
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_link_to(name = nil, options = nil, html_options = nil, &block)
	  active_class = html_options[:active] || "active"
	  html_options.delete(:active)
	  html_options[:class] = "#{html_options[:class]} #{active_class}" if current_page?(options)
	  link_to(name, options, html_options, &block)
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def format(string)
<<<<<<< HEAD
		RDiscount.new(string).to_html.html_safe
	end
	
=======

		RDiscount.new(string).to_html.html_safe

	end

>>>>>>> slideOK
end

app/views/categories/home.html.erb
<section class="video_form">

  <div id="slider" class="eight columns flexslider">
    <ul class="slides">
      <li>
        <h2>We use accelerated learning techniques with our own Learn Realquick<sup>TM</sup> method</h2>
        <div class="transp"></div>
        <%= image_tag "slide_girl.jpg" %>
      </li>
      <li>
        <h2>Our English Courses are structured to cater for your level and objectives</h2>
        <%= image_tag "students_activity.jpg" %>
        <div class="transp"></div>
      </li>
      <li>
        <h2>Looking for short courses to improve your English quickly to get a job?</h2>
        <%= image_tag "slide_girl_career.jpg" %>
        <div class="transp"></div>
      </li>
    </ul>
  </div>

  <%= render :partial => 'shared/aweberform' %>

</section>

<section class="eight columns">

    <div class="postslist">
        <div class="single_post group">

      <% @posts.each do |post| %>
        <div class="single_post group">

            <div class="post_details">
              <h2><%= link_to post.title, category_post_path(post.category, post) %></h2>
              <%= image_tag post.image(:header), class: "post_image" %>
              <p><%= format truncate post.body, length: 100 %></p>
            </div>

        </div>
      <% end %>

        </div>
    </div>

</section>

<section class="four columns">

<%= render :partial => 'shared/categoriesmenu' %>

</section>

app/views/categories/index.html.erb
<section class="eight columns">

    <div class="postslist">
      <% @posts.each do |post| %>
        <div class="single_post group">

            <div class="post_details">
	            <h2><%= link_to post.title, category_post_path(post.category, post) %></h2>
              <%= image_tag post.image(:header), class: "post_image" %>
              <p><%= format truncate post.body, length: 100 %></p>
            </div>

        </div>
      <% end %>

    </div>

</section>


<section class="four columns post_menu">

  <div>
    <%= render :partial => 'shared/search' %>
  </div>

  <div>
    <%= render :partial => 'shared/blogsubscribeaweber' %>
  </div>

  <div>
    <%= render :partial => 'shared/categoriesmenu' %>
  </div>


</section>

app/views/categories/show.html.erb
<section class="eight columns">

	<% @category.posts.order('created_at desc').each do |post| %>

		<div class="post_details">
			<h2><%= link_to post.title, category_post_path(@category, post) %></h2>
			<%= image_tag post.image(:header), class: "post_image" %>
			<p><%= format truncate post.body, length: 300 %></p>
		</div>

	<% end %>

</section>

<section class="four columns">

  <div>
    <%= render :partial => 'shared/search' %>
  </div>

  <div>
    <%= render :partial => 'shared/blogsubscribeaweber' %>
  </div>
  
  <div>
    <%= render :partial => 'shared/categoriesmenu' %>
  </div>

</section>

app/views/contents/chooseus.html.erb
<section class="chooseus">

	<div class="ten columns offset-by-one">
		<%= image_tag "chooseus.jpg", class: "ten columns" %>
	</div>
	<div class="ten columns offset-by-one">
		<br />
		<hr class="light">
	</div>
	<div class="row">

		<div class="four columns">
			<h2><i class="fa fa-signal"></i> <%= t('.chooseustitle1') %></h2>
			<hr class="light">
			<div class="row">
				<h3><%= t('.chooseus1_subtitle1_html') %></h3>
				<p><%= t('.chooseus1_text1_html') %></p>
				<%= active_link_to t('.findout'), memberships_path, class: "button" %>
			</div>
			<div class="row">
				<h3><%= t('.chooseus1_subtitle2') %></h3>
				<p><%= t('.chooseus1_text2_html') %></p>
				<%= active_link_to t('.findout'), method_path, class: "button" %>
			</div>
			<div class="row">
				<h3><%= t('.chooseus1_subtitle3') %></h3>
				<br />
				<%= image_tag "method2_purplestone.jpg" %>
				<br /><br />
				<p><%= t('.chooseus1_text3') %></p>
				<%= active_link_to t('.findout'), memberships_path, class: "button" %>
			</div>
			<div class="row">
				<h3><%= t('.chooseus1_subtitle4') %></h3>
				<p><%= t('.chooseus1_text4') %></p>
				<%= active_link_to t('.findout'), memberships_path, class: "button" %>
			</div>
			<div class="row">
				<h3><%= t('.chooseus1_subtitle5') %></h3>
				<p><%= t('.chooseus1_text5') %></p>
				<%= active_link_to t('.findout'), memberships_path, class: "button" %>
			</div>
		</div>

		<div class="four columns">
			<h2><i class="fa fa-pencil"></i> <%= t('.chooseustitle2') %></h2>
			<hr class="light">

			<div class="row">
				<h3><%= t('.chooseus2_subtitle1') %></h3>
				<br />
				<%= image_tag "chooseus3.jpg" %>
				<br /><br />
				<p><%= t('.chooseus2_text1') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus2_subtitle2') %></h3>
				<br />
				<%= image_tag "boy_reading.jpg" %>
				<br /><br />
				<p><%= t('.chooseus2_text2') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus2_subtitle3') %></h3>
				<p><%= t('.chooseus2_text3_part1') %><%= active_link_to t('.chooseus2_text3_part2'), resources_path(:anchor => "acommodation"), class: "link" %><%= t('.chooseus2_text3_part3') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus2_subtitle4') %></h3>
				<p><%= t('.chooseus2_text4_part1') %><%= active_link_to "Learn Realquick Method", method_path, class: "link" %><%= t('.chooseus2_text4_part2_html') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus2_subtitle5') %></h3>
				<br />
				<%= image_tag "students_activity.jpg" %>
				<br /><br />
				<p><%= t('.chooseus2_text5') %></p>
				<%= active_link_to t('.findout'), method_path, class: "button" %>
			</div>
		</div>

		<div class="four columns">
			<h2><i class="fa fa-certificate"></i> <%= t('.chooseustitle3') %></h2>
			<hr class="light">
			<div class="row">
				<h3><%= t('.chooseus3_subtitle1') %></h3>
				<p><%= t('.chooseus3_text1_html') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus3_subtitle2') %></h3>
				<p><%= t('.chooseus3_text2') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus3_subtitle3') %></h3>
				<p><%= t('.chooseus3_text3') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus3_subtitle4') %></h3>
				<p><%= t('.chooseus3_text4') %></p>
			</div>
			<div class="row">
				<h3><%= t('.chooseus3_subtitle5') %></h3>
				<br />
				<%= image_tag "academy_activity.jpg" %>
				<br /><br />
				<p><%= t('.chooseus3_text5') %></p>
				<br />
				<%= image_tag "lily.jpg" %>
				<note>Lily, teacher</note>
			</div>
		</div>

	</div>

	<div class="row">

		<div class="twelve columns">
			<h2><i class="fa fa-users"></i>  <%= t('.chooseustitle4') %></h2>
			<hr class="light">			
		</div>

		<div class="four columns">
			<h3><%= t('.chooseus4_subtitle1') %></h3>
			<p><%= t('.chooseus4_text1') %></p>
			<hr class="light">
			<h3>Maki, Japan</h3>
			<hr class="light">
			<note><%= t('.chooseus4_note1') %></note>
		</div>
		<div class="four columns">
			<h3><%= t('.chooseus4_subtitle2') %></h3>
			<p><%= t('.chooseus4_text2') %></p>
			<hr class="light">
			<h3>Marcony, Brazil</h3>
			<hr class="light">
			<note><%= t('.chooseus4_note2') %></note>
		</div>
		<div class="four columns">
			<h3><%= t('.chooseus4_subtitle3') %></h3>
			<p><%= t('.chooseus4_text3') %></p>
			<hr class="light">
			<h3>Beata, Poland</h3>
			<hr class="light">
			<note><%= t('.chooseus4_note3') %></note>
		</div>

	</div>

</section>

app/views/contents/resources.html.erb
<section class="resources">

	<div class="row resourses_top">
		<div class="four columns offset-by-one slide">
			<h4>Accomodation and Internships packages</h4>
			<h3>We are developing some packages to give you the most customized attention.
			<br />So, please keep in touch and come to this section in the future to see what we have prepared for you</h3>
			<hr class="light">
			<p><i class="fa fa-arrow-circle-down"></i> <%= active_link_to "Internships", resources_path(:anchor => "internship"), class: "link" %><br />
			<i class="fa fa-arrow-circle-down"></i> <%= active_link_to "Career Advice", resources_path(:anchor => "career"), class: "link" %><br />
			<i class="fa fa-arrow-circle-down"></i> <%= active_link_to "Accomodation", resources_path(:anchor => "acommodation"), class: "link" %>
			</p>

		</div>
		<div class="three columns offset-by-one slide">
			<p class="button"><i class="fa fa-home"></i> Accomodation <br />+ English Lessons</p>
			<p class="button"><i class="fa fa-home"></i> Accomodation <br />+ Career Advice</p>
			<p class="button"><i class="fa fa-home"></i> Accomodation <br />+ English Lesson <br />+ Career Advice</p>
		</div>

		<div class="three columns slide">
			<p class="button"><i class="fa fa-puzzle-piece"></i> Internships <br />+ English Lessons</p>
			<p class="button"><i class="fa fa-puzzle-piece"></i> Internships <br />+ Career Advice</p>
			<p class="button"><i class="fa fa-puzzle-piece"></i> Internships <br />+ English Lesson <br />+ Career Advice</p>
			<br />
		</div>

	</div>

	<div class="row">

		<div class="eight columns offset-by-two">

			<h2 id="internship"><i class="fa fa-puzzle-piece"></i> <%= t('.internships') %></h2>
			<hr class="light">
			<div class="">
				<%= image_tag "internship_purplestone.jpg", alt: "Internships in Purple Stone Academy" %>
			</div>
			<br />
			<p><%= t('.internshipstext') %></p>
			<ul class="disc">
				<li><%= t('.internshipsli1') %></li>
				<li><%= t('.internshipsli2') %></li>
				<li><%= t('.internshipsli3') %></li>
				<li><%= t('.internshipsli4') %></li>
				<li><%= t('.internshipsli5') %></li>
				<li><%= t('.internshipsli6') %></li>
				<li><%= t('.internshipsli7') %></li>
			</ul>

			<br />
			<hr>
			<br />
					
		</div>
		
	</div>


	<div class="row">

		<div class="eight columns offset-by-two">

			<h2 id="career"><i class="fa fa-book"></i> <%= t('.careeradvice') %></h2>
			<hr class="light">
			<div class="">
				<%= image_tag "careeradvice_purplestone.jpg", alt: "Career Advice in Purple Stone Academy" %>
			</div>
			<br /><br />
			<div class="row">

				<div class="three columns">
					<h3><%= t('.adviceandsupport') %></h3>
					<p><%= t('.adviceandsupporttext') %></p>
				</div>
				<div class="three columns offset-by-one">
					<h3><%= t('.cvwriting') %></h3>
					<p><%= t('.cvwritingtext') %></p>
				</div>

			</div>

			<div class="row">

				<div class="three columns">
					<h3><%= t('.applicationstojobs') %></h3>
					<p><%= t('.applicationstojobstext') %></p>
				</div>
				<div class="three columns offset-by-one">
					<h3><%= t('.training') %></h3>
					<p><%= t('.trainingtext') %></p>
				</div>
				
			</div>

			<div class="row">
				<p><%= t('.consultation') %></p>

				<note><%= t('.getintouch') %><%= mail_to "careers@purplestoneacademy.com", "careers@purplestoneacademy.com" %></note><br /><br />
				<note><%= t('.getintouch2') %><%= link_to "www.purplestonecareeradvice.com", "http://www.purplestonecareeradvice.com" %></note>
			</div>
			
			<br />
			<hr>
			<br />

		</div>
		
	</div>

	<div class="row">

		<div class="eight columns offset-by-two">

			<h2 id="acommodation"><i class="fa fa-home"></i> <%= t('.accomodation') %></h2>
			<hr class="light">
			<div class="">
				<%= image_tag "casa-psr_3.jpg", alt: "Accomodation in Purple Stone Academy" %>
			</div>
			<br /><br />
			<div class="row">

				<div class="three columns">
					<h3><%= t('.accomodationtitle1') %></h3>
					<p><%= t('.accomodationtext1') %></p>
				</div>
				<div class="three columns offset-by-one">
					<h3><%= t('.accomodationtitle2') %></h3>
					<p><%= t('.accomodationtext2') %></p>
				</div>

			</div>

			<div class="row">

				<div class="three columns">
					<h3><%= t('.accomodationtitle3') %></h3>
					<p><%= t('.accomodationtext3') %></p>
				</div>
				<div class="three columns offset-by-one">
					<h3><%= t('.accomodationtitle4') %></h3>
					<p><%= t('.accomodationtext4') %></p>
				</div>
				
			</div>

			<div class="row">

				<div class="seven columns">
					<h3><%= t('.accomodationtitle5') %></h3>
					<p><%= t('.accomodationtext5') %></p>
				</div>
				
			</div>
			
			<note><%= t('.pleasecontact') %><%= mail_to "maria@purplestonerooms.com", "maria@purplestonerooms.com" %></note><br /><br />
			<note><%= t('.alternatively') %><%= mail_to "lily@purplestonerooms.com", "lily@purplestonerooms.com" %></note>
			
		</div>
		
	</div>

</section>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Purple Stone Academy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="container">
		<div class="row">
			<h1 id="top" class="three columns">
				<%= link_to(root_path) do %>
				<%= image_tag "logo_psa.png" %>
				<% end %>
			</h1>

			<div class="four columns">
				<h2 class="slogan">Learn English Fast</h2>
			</div>

			<div class="five columns header_right_side">
				<div class="header_right">
					<phone class="muted"><span class="fa-stack">
					<i class="fa fa-circle fa-stack-2x"></i>
					<i class="fa fa-phone fa-stack-1x fa-inverse"></i>
					</span> 0207 247 1440</phone>
					<div>
					<div id="languages">
						<%= form_tag root_path, class: 'locale', :method => :get do %>
							<%= select_tag 'set_locale',
								options_for_select(LANGUAGES, I18n.locale.to_s),
								onchange: 'this.form.submit()' %>
							<%= submit_tag 'submit' %>
							<%= javascript_tag "$('.locale input').hide()" %>
						<% end %>
					</div>
					</div>
					<div class="stay-in-touch-icons">
						<a class="twitter" href="https://twitter.com/PurpleStoneAc" target="_blank" title="Follow us on Twitter">Follow us on Twitter</a>
						<a class="facebook" href="https://www.facebook.com/PurpleStoneAcademyLtd" target="_blank" title="Follow us on Facebook">Follow us on Facebook</a>
						<a class="google-plus" href="https://plus.google.com/b/117791296366751294284/117791296366751294284" target="_blank" title="Follow us on Google Plus">Follow us on Google Plus</a>
						<a class="linkedin" href="http://www.linkedin.com/groups/Purple-Stone-Academy-6543537?home=&gid=6543537" target="_blank" title="Follow us on Linkedin">Follow us on Linkedin</a>
						<a class="pinterest" href="http://www.pinterest.com/lilypurplestone/boards" target="_blank" title="Follow us on Pinterest">Follow us on Pinterest</a>
						<a class="youtube" href="http://www.youtube.com/watch?v=1x0vD3r9mbk" target="_blank" title="Follow us on Youtube">Follow us on Youtube</a>
					</div>
				</div>

			</div>
		</div> <!--  .row -->

		<nav class="row">
			<ul id="menu">
				<li><%= active_link_to t('.home'), root_path, class: "first" %></li>
				<li><%= active_link_to t('.courses'), courses_path, class: "link" %></li>
				<li><%= active_link_to t('.method'), method_path, class: "link" %></li>
				<li><%= active_link_to t('.memberships'), memberships_path, class: "link" %></li>
				<li><%= active_link_to "BLOG", categories_path, class: "link" %></li>
				<li><%= active_link_to t('.chooseus'), chooseus_path, class: "link" %></li>
				<li><%= active_link_to t('.stories'), stories_path, class: "link" %></li>
				<li><%= active_link_to t('.resources'), resources_path, class: "link" %></li>
				<li><%= active_link_to t('.contact'), aweberform_path, class: "last" %></li>
			</ul>
		</nav> <!--  .row -->

	</header> <!--  .container -->


	<div class="body_background">
		<div class="container content">
			<% flash.each do |key, value| %>
				<div class="twelve columns flash <%= key %>"><%= value %></div>
			<% end %>

			<article class="row">
				<%= yield %>
			</article>

			<p id="back-top">
				<a href="#top"><span></span>Back to top</a>
			</p>

			<footer>
				<div class="row">
					<div class="footer_one">
						<div class="seven columns about">
							<h2><i class="fa fa-info-circle"></i> <%= t('.aboutustitle') %></h2>
							<h4><%= t('.whatis') %></h4>
							<p><%= t('.aboutustext') %></p>
						</div>
						<div class="four columns offset-by-one affiliate">
							<h2><%= t('.affiliatetitle') %></h2>
							<p><%= t('.affiliatetext') %></p>
							<%= mail_to "lily@purplestoneacademy.com", t('.affiliatebutton'), class: "button" %>				
						</div>
					</div>
				</div>

				<nav class="row">
					<ul id="menu">
						<li><%= active_link_to t('.home'), root_path, class: "first" %></li>
						<li><%= active_link_to t('.courses'), courses_path, class: "link" %></li>
						<li><%= active_link_to t('.method'), method_path, class: "link" %></li>
						<li><%= active_link_to t('.memberships'), memberships_path, class: "link" %></li>
						<li><%= active_link_to "BLOG", categories_path, class: "link" %></li>
						<li><%= active_link_to t('.chooseus'), chooseus_path, class: "link" %></li>
						<li><%= active_link_to t('.stories'), stories_path, class: "link" %></li>
						<li><%= active_link_to t('.resources'), resources_path, class: "link" %></li>
						<li><%= active_link_to t('.contact'), aweberform_path, class: "last" %></li>
					</ul>
				</nav> <!--  #main_nav --> <!--  .row -->

				<div class="footer_two">
					<h1 class="three columns">
						<%= link_to(root_path) do %>
						<%= image_tag "logo_psa_white.png" %>
						<% end %>
					</h1>

					<div class="four columns">
						<h2 class="slogan">Learn English Fast</h2>
					</div>

					<div class="four columns offset-by-one">
						<div class="address">
							<p class="muted"><span class="fa-stack">
							<i class="fa fa-square-o fa-stack-2x"></i>
							<i class="fa fa-phone fa-stack-1x"></i>
							</span> 0207 247 1440</p>
							<p>101 Whitechapel High Street<br />
							E1 7RA, London<br />						
							<i class="fa fa-map-marker"></i> Aldgate East</p>
						</div>
					</div>
					
				</div>

				<div class="row ourcompanies">
					<div class="twelve columns">
						<p><%= t('.ourcompanies') %></p>
						<br />
					</div>

					<div class="three columns">
						<%= link_to "http://www.purplestonegroup.com/" do %>
						<%= image_tag "logo_psg_white.png", width: '150' %>
						<% end %>
					</div>
					<div class="three columns">
						<%= link_to "http://www.purplestonecareeradvice.com/" do %>
						<%= image_tag "logo_psca_white.png", width: '185' %>
						<% end %>
					</div>
					<div class="three columns">
						<%= link_to "http://www.purplestonerooms.com/" do %>
						<%= image_tag "logo_psr_white.png", width: '150' %>
						<% end %>
					</div>
					<div class="three columns">
						<%= link_to "http://www.pstonemedia.com/" do %>
						<%= image_tag "logo_psm_white.png", width: '150' %>
						<% end %>
					</div>

				</div>

				<div class="row copy">
					<p class="four columns">&copy; <%= Date.today.year %> Purple Stone Group Ltd</p>
					<div>
						<ul id="menu_footer" class="six columns">
							<li><%= link_to "Terms and Conditions", terms_path %></li>
							<li><%= link_to "Privacy Policy", privacy_path %></li>
							<li><%= link_to "Design: Purple Stone Media", "http://www.pstonemedia.com/" %></li>
						</ul>
					</div>
				</div>

			</footer>
		</div> <!--  .container -->
	</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33665567-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>

app/views/posts/search.html.erb
<section class="seven columns">

    <div class="postslist">
      <% @posts.each do |post| %>
        <div class="single_post group">

            <div class="post_details">
	            <h2><%= link_to post.title, category_post_path(post.category, post) %></h2>
              <%= image_tag post.image(:header), class: "post_image" %>
              <p><%= format post.body %></p>
            </div>

        </div>
      <% end %>

    </div>

</section>


<section class="four columns post_menu">

  <div>
    <%= render :partial => 'shared/search' %>
  </div>

  <div>
    <%= render :partial => 'shared/blogsubscribeaweber' %>
  </div>

  <div>
    <%= render :partial => 'shared/categoriesmenu' %>
  </div>


</section>

app/views/shared/_categoriesmenu.html.erb
<div class="post_menu">
	
	<h3>Categories</h3>
	
	<ul>
		<% @categories.each do |category| %>
			<li><%= link_to truncate(category.name, :length => 40), category_path(category) %></li>
		<% end %>
	</ul>

</div>